import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :pii_detector, PiiDetectorWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "sePe1DDmGszgeujRmK3kk7fwuIyDB/ZIgp5h8Kyk2MjkGePQZeltLojcN9zemNqO"

# slack app config
config :pii_detector, :slack,
  app_id: "A08M42LM8CR",
  client_id: "8709482003092.8718088722433",
  secret: "",
  signing_secret: "",
  verification_token: ""

config :slack, api_token: ""
# cludflare config
config :pii_detector, :cloudflare,
  api_token: "",
  account_id: "2532c238321714c590816151bbbb15e5"

# notion config
config :pii_detector, :notion, api_token: ""

# google ai config

config :pii_detector, google_ai_api_key: ""

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :pii_detector, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
